
environment:
  matrix:

   - job_name: Windows
     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
     configuration: Debug
     platform: x64

   - job_name: Windows
     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
     configuration: Release
     platform: x64

   - job_name: Windows
     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
     configuration: Retail
     platform: x64

   - job_name: Linux
     APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2204
     buildcfg: debug64

   - job_name: Linux
     APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2204
     buildcfg: release64

   - job_name: Linux
     APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2204
     buildcfg: retail64

   - job_name: OSX
     APPVEYOR_BUILD_WORKER_IMAGE: macOS-sonoma
     buildcfg: debug64

   - job_name: OSX
     APPVEYOR_BUILD_WORKER_IMAGE: macOS-sonoma
     buildcfg: release64

   - job_name: OSX
     APPVEYOR_BUILD_WORKER_IMAGE: macOS-sonoma
     buildcfg: retail64

shallow_clone: true

install:
- git submodule init
- git submodule update

for:
  
# ======================================
# Windows
# ======================================

  -
    matrix:
      only:
      - job_name: Windows
      - QTDIR: C:\Qt\6.5.3\msvc2019_64
    
    init:
    - set QTDIR=C:\Qt\6.5.3\msvc2019_64
    - git clone --depth 1 https://github.com/rjpcomputing/luaforwindows luaforwindows
    - copy %cd%\luaforwindows\files\lua5.1.exe %cd%\luaforwindows\files\lua.exe
    - set PATH=%cd%\luaforwindows\files;C:\Qt\6.5.3\msvc2019_64\bin;%PATH%
    - git clone --recursive --depth 1 https://github.com/milostosic/MTuner  MTuner

    install:
      - MTuner\build\tools\bin\windows\genie.exe --file=MTuner\src\MTuner\genie\genie.lua vs2022

    build: ../.build/windows/vs2022/MTuner/projects/MTuner.sln

# ======================================
# Linux
# ======================================

  -
    matrix:
      only:
      - job_name: Linux

    init:
      - sudo apt install -y lua5.3 lua-filesystem
      - export QTDIR="$HOME/Qt/6.5.3/gcc_64"
      - export PATH="$HOME/Qt/6.5.3/gcc_64/bin:$HOME/Qt/6.5.3/gcc_64/libexec:/home/appveyor/Qt/6.5.3/gcc_64/libexec:$PATH"
      - export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$HOME/Qt/6.5.3/gcc_64/lib/pkgconfig"
      - git clone --recursive --depth 1 https://github.com/milostosic/MTuner    MTuner
      - git clone --depth 1 https://github.com/bkaradzic/GENie                  GENie
      - cd GENie && make && cd ..

    install:
      - ./GENie/bin/linux/genie --file=MTuner/src/MTuner/genie/genie.lua --gcc=linux-gcc gmake
  
    build_script:
      - cd MTuner/.build/linux/linux-gcc/MTuner/projects/
      - make config=${buildcfg}
     
# ======================================
# OSX
# ======================================

  -
    matrix:
      only:
      - job_name: OSX

    init:
      - export QTDIR="$HOME/Qt/6.5.3/macos/" 
      - export PATH="$HOME/Qt/6.5.3/macos/bin:$HOME/Qt/6.5.3/macos/libexec:$PATH"
      - export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$HOME/Qt/6.5.3/macos/lib/pkgconfig"
      - curl -L -R -O https://www.lua.org/ftp/lua-5.4.7.tar.gz
      - tar zxf lua-5.4.7.tar.gz
      - cd lua-5.4.7 && sudo make all test && sudo make install && cd ..
      - git clone --recursive --depth 1 https://github.com/milostosic/MTuner MTuner
      - git clone --depth 1 https://github.com/bkaradzic/GENie GENie  # build GENie from source: we don't know the target CPU, can't use ARM binary from 'build'
      - cd GENie && make && cd ..
    
    install:
      - ./GENie/bin/darwin/genie --file=MTuner/src/MTuner/genie/genie.lua --gcc=osx-x64 gmake
    
    build_script:
      - cd MTuner/.build/osx/clang/MTuner/projects/
      - make config=${buildcfg}
