
environment:
  matrix:

   - job_name: OSX
     APPVEYOR_BUILD_WORKER_IMAGE: macOS-monterey
     buildcfg: debug64

   - job_name: OSX
     APPVEYOR_BUILD_WORKER_IMAGE: macOS-monterey
     buildcfg: release64

   - job_name: OSX
     APPVEYOR_BUILD_WORKER_IMAGE: macOS-monterey
     buildcfg: retail64

shallow_clone: true

install:
- git submodule init
- git submodule update

for:
  

# ======================================
# OSX
# ======================================

  -
    matrix:
      only:
      - job_name: OSX

    init:
    - if [ ! -d ../vcpkg ]; then git clone https://github.com/microsoft/vcpkg.git ../vcpkg ; fi
    - "(cd ../vcpkg && git pull && ./bootstrap-vcpkg.sh)"
    - export VCPKG_DIR=`dirname $(pwd)/../vcpkg/vcpkg`
    - export QTDIR="$HOME/Qt/6.4/macos"
    - export PATH="$HOME/Qt/6.4/macos/bin:$HOME/Qt/6.4/macos/share/qt/libexec:/Users/appveyor/Qt/6.4/macos/libexec:$PATH"
    - export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$HOME/Qt/6.4/macos/lib/pkgconfig"
    - export QTDIR_GMAKE_x64="$HOME/Qt/6.4/macos"
    - export QTDIR_GMAKE_x86="$HOME/Qt/6.4/macos" 
    - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - brew update
    - brew install lua qt6
    - git clone --recursive --depth 1 https://github.com/milostosic/MTuner       MTuner
    
    install:
      - ./MTuner/build/tools/bin/darwin/genie --file=MTuner/src/MTuner/genie/genie.lua --gcc=osx gmake
    
    build_script:
      - cd MTuner/.build/osx/clang/MTuner/projects/
      - make config=${buildcfg}
